sudo: 'required'
language: java
cache:
  directories:
  - "$HOME/.cache"

services:
- docker

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
      docker build -t $DOCKER_USERNAME/cryptonite:latest . ;
      docker push $DOCKER_USERNAME/cryptonite ;
    fi

deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy"
  skip_cleanup: true
  on:
    tags: true